apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: particular-asb-sender-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sender
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sender-container
        image: adamralph/particular-asb-sender:latest
        env:
        - name: ASB_CONNECTION_STRING
          value: "<<ENTER ASB CONNECTION STRING>>"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: particular-asb-receiver-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: receiver
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: receiver-container
        image: adamralph/particular-asb-receiver:latest
        env:
        - name: ASB_CONNECTION_STRING
          value: "<<ENTER ASB CONNECTION STRING>>"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: particular-asb-service-control-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-control
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: service-control-container
        image: adamralph/particular-asb-service-control
        ports:
          - containerPort: 33333
        env:
        - name: ServiceControl_ConnectionString
          value: "<<ENTER ASB CONNECTION STRING>>"
  selector:
    matchLabels:
      app: service-control
---
apiVersion: v1
kind: Service
metadata:
  name: service-control-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 33333
  selector:
    app: service-control
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: particular-service-pulse-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-pulse
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: service-pulse-container
        image: particular/servicepulse
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: service-pulse
---
apiVersion: v1
kind: Service
metadata:
  name: service-pulse-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: service-pulse
